# Generated by Django 4.2.3 on 2023-08-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popugauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='popug',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='popug',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
