# Generated by Django 4.2.3 on 2023-08-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popugauth', '0002_alter_popug_managers_alter_popug_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='popug',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
