# Generated by Django 4.2.3 on 2023-08-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popugauth', '0003_popug_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='popug',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates whether the user is super!', verbose_name='superuser status'),
        ),
    ]
